version: "3.8"
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  # You need to enter into the pgAdmin interface
  # Navigate to localhost:8500.
  # Connect the DB
  # On the General tab write zero2prod on "Name" (zero2prod can be anything else)
  # On the Conenction tab write "db" without commas in Host name/addresses (No http or anything else... just db)
  # Check that the port is 5432 and click save. Remember to put the user (postgress) and password (password)
  pgadmin:
    image: dpage/pgadmin4:6.11
    ports:
      - "8500:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@a.com
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  db:
    driver: local
